version: "2"
services:
  node_web:
    build: .
    container_name: "meli_node"
    volumes:
      - ".:/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
      - redis_registers
      - redis_cache
  mongo_db:
    container_name: "Mongo_reg"
    image: mongo:4.2.2
    ports:
      - "27017:27017"
  redis_registers:
    container_name: "Redis_reg"
    image: redis:5.0.7
    ports:
      - "6379:6379"
  redis_cache:
    container_name: "Redis_Cache"
    image: redis:5.0.7
    ports:
      - "6380:6379"
